#!/bin/bash
# Changelog 快速查詢指令

echo "📚 NotebookLM Changelog 快速查詢"
echo "================================"
echo ""
echo "可用命令："
echo ""
echo "1️⃣  查看 Studio 功能 (v0.0.1) 概要："
echo "   cat changelog/CHANGELOG_v0.0.1_studio.md"
echo ""
echo "2️⃣  查看認證功能 (v0.0.0) 概要："
echo "   cat changelog/CHANGES_v0.0.0_auth-and-security.md"
echo ""
echo "3️⃣  查看快速摘要："
echo "   cat changelog/SUMMARY.txt"
echo ""
echo "4️⃣  查看完整 Changelog 指南："
echo "   cat changelog/README.md"
echo ""
echo "5️⃣  查看 Studio 完整改動 (第一頁)："
echo "   head -100 changelog/studio-feature-v0.0.1.diff"
echo ""
echo "6️⃣  查看 Studio 完整改動 (分頁)："
echo "   less changelog/studio-feature-v0.0.1.diff"
echo ""
echo "7️⃣  統計 Studio 改動行數："
echo "   diffstat changelog/studio-feature-v0.0.1.diff"
echo ""
echo "8️⃣  在編輯器中打開 diff："
echo "   code changelog/studio-feature-v0.0.1.diff"
echo ""
echo "================================"
echo ""
echo "📊 版本統計："
echo "   v0.0.1 (Studio)：17 檔案, 1,665 行新增, 3 行刪除"
echo "   v0.0.0 (認證)：30 檔案, 2,346 行新增, 1,233 行刪除"
