"""
extract_icons.py — Build-time script to extract SVG path data from react-icons source files.

Usage:
    python backend/app/scripts/extract_icons.py

Reads from:
    react-icons/fa/index.js  (FontAwesome 5)
    react-icons/md/index.js  (Material Design)

Outputs:
    backend/app/data/icon_registry.json
    frontend/src/lib/icon-registry.ts
"""
import json
import re
import sys
from pathlib import Path

# Paths relative to project root
PROJECT_ROOT = Path(__file__).parents[3]  # notebooklm/
REACT_ICONS_DIR = PROJECT_ROOT / "react-icons"
OUTPUT_JSON = Path(__file__).parent.parent / "data" / "icon_registry.json"
OUTPUT_TS = PROJECT_ROOT / "frontend" / "src" / "lib" / "icon-registry.ts"

# Icons referenced in SLIDES_PROMPT
TARGET_ICONS = {
    "fa": [
        "FaRocket", "FaShieldAlt", "FaChartLine", "FaUsers", "FaCog",
        "FaLightbulb", "FaDatabase", "FaCloud", "FaCode", "FaGlobe",
        "FaLock", "FaBolt", "FaStar", "FaCheck", "FaArrowUp",
        "FaExchangeAlt", "FaBalanceScale", "FaHandshake", "FaTrophy",
        "FaFlag", "FaHeart", "FaMoneyBillWave", "FaClipboardList",
        "FaSearchDollar", "FaBullseye", "FaProjectDiagram", "FaSitemap",
        "FaRegCalendarAlt", "FaUserTie", "FaBriefcase",
    ],
    "md": [
        "MdDashboard", "MdAnalytics", "MdSecurity", "MdSpeed",
        "MdBuild", "MdInsights", "MdTrendingUp", "MdCompareArrows",
        "MdTimeline", "MdAssessment",
    ],
}


def extract_paths_from_child(child_list: list) -> list[str]:
    """Recursively collect all SVG path 'd' attributes from GenIcon child tree."""
    paths = []
    for item in child_list:
        if not isinstance(item, dict):
            continue
        if item.get("tag") == "path":
            d = item.get("attr", {}).get("d", "")
            if d:
                paths.append(d)
        if item.get("child"):
            paths.extend(extract_paths_from_child(item["child"]))
    return paths


def extract_icons_from_file(js_path: Path, icon_names: list[str]) -> dict[str, dict]:
    """Extract SVG data for specified icon names from a react-icons index.js."""
    source = js_path.read_text(encoding="utf-8")
    result = {}

    for icon_name in icon_names:
        # Match: module.exports.FaRocket = function FaRocket (props) { return GenIcon({...})(props); };
        pattern = (
            rf"module\.exports\.{re.escape(icon_name)}\s*=\s*function\s+\w+\s*\(props\)\s*\{{\s*"
            rf"return GenIcon\((\{{.*?\}})\)\(props\);\s*\}};"
        )
        match = re.search(pattern, source, re.DOTALL)
        if not match:
            print(f"  WARNING: {icon_name} not found in {js_path.name}", file=sys.stderr)
            continue

        try:
            icon_data = json.loads(match.group(1))
        except json.JSONDecodeError as e:
            print(f"  ERROR: Failed to parse {icon_name}: {e}", file=sys.stderr)
            continue

        view_box = icon_data.get("attr", {}).get("viewBox", "0 0 24 24")
        paths = extract_paths_from_child(icon_data.get("child", []))

        if paths:
            result[icon_name] = {"viewBox": view_box, "paths": paths}
            print(f"  ✓ {icon_name} ({len(paths)} path(s))")
        else:
            print(f"  WARNING: {icon_name} has no paths", file=sys.stderr)

    return result


def main():
    registry: dict[str, dict] = {}

    for pack, icon_names in TARGET_ICONS.items():
        js_file = REACT_ICONS_DIR / pack / "index.js"
        if not js_file.exists():
            print(f"ERROR: {js_file} not found", file=sys.stderr)
            sys.exit(1)
        print(f"\nExtracting from {js_file.relative_to(PROJECT_ROOT)}:")
        icons = extract_icons_from_file(js_file, icon_names)
        registry.update(icons)

    # Write JSON registry for backend
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(registry, ensure_ascii=False, indent=2))
    print(f"\n✓ Written {len(registry)} icons to {OUTPUT_JSON.relative_to(PROJECT_ROOT)}")

    # Write TypeScript registry for frontend
    ts_lines = [
        "// AUTO-GENERATED by backend/app/scripts/extract_icons.py — do not edit manually",
        "",
        "export interface IconEntry {",
        "    viewBox: string;",
        "    paths: string[];",
        "}",
        "",
        "export const ICON_REGISTRY: Record<string, IconEntry> = ",
    ]
    ts_lines.append(json.dumps(registry, ensure_ascii=False, indent=2) + ";")
    ts_lines.append("")
    OUTPUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_TS.write_text("\n".join(ts_lines))
    print(f"✓ Written TypeScript registry to {OUTPUT_TS.relative_to(PROJECT_ROOT)}")

    missing = [
        name
        for names in TARGET_ICONS.values()
        for name in names
        if name not in registry
    ]
    if missing:
        print(f"\nWARNING: {len(missing)} icons not extracted: {missing}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
